add default option fetchsize of MLSQLJDBC
allwefantasy/mlsql pull request #12
Opened 2021-11-18 15:35 UTC by hellozepp

In the following pr, spark supports the jdbc parameter fetch_size to be set to a negative number. Namely, to allow data fetch in stream manner (row-by-row fetch) against MySQL database.
```
https://github.com/apache/spark/pull/26244
```

On this basis, we provide a default value of fetch_size to use row-by-row fetch, which can avoid loading too large data to cause OOM.

2021-11-18 15:38 UTC, hellozepp commented
# 复现方式
我在数据库中插入了超过512M的数据，并设置如下JVM参数：
```
-Xms512m  -Xmx512m
```

通过`directQuery`方式`load`全量表，我得到了下面的异常：
```
Job aborted due to stage failure: Task 0 in stage 27.0 failed 1 times, most recent failure: Lost task 0.0 in stage 27.0 (TID 265) (192.168.0.102 executor driver): java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3417)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:471)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3115)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2344)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2739)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.compute(JDBCRDD.scala:304)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$2716/53833777.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

2021-11-18 15:42 UTC, hellozepp commented
# Effect after repair
Without specifying fetchSize in sql, I can use `load` to pull all table data normally.
![image](https://user-images.githubusercontent.com/20615623/142447588-ae1021d2-01f5-4650-b644-1a41e3e285cf.png)

2021-11-20 05:41 UTC, allwefantasy requested changes

2021-11-20 05:41 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/JDBCSource.scala
> +  def fillJDBCOptions(reader: DataFrameReader, config: DataSourceConfig, formatName: String, dbSplitter: String): (Option[String], Option[String]) = {
Notice that this is only happen in MySQL JDBC Driver. According to your refractor, the change will infect all jdbc data source.

2021-11-20 05:41 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/JDBCSource.scala
> +    url = url.map(x => if (x.contains("useCursorFetch")) x else s"$x&useCursorFetch=true")
The url parameters only supported by MySQL JDBC Driver. we should do like this.

2021-11-20 08:43 UTC, chncaesar commented
Please update mlsql-docs accordingly.

2021-11-20 12:20 UTC, hellozepp commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/JDBCSource.scala
> +  def fillJDBCOptions(reader: DataFrameReader, config: DataSourceConfig, formatName: String, dbSplitter: String): (Option[String], Option[String]) = {
Yes, this interface refers to all jdbc sources in general, I changed it

2021-11-20 12:21 UTC, hellozepp commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/JDBCSource.scala
> +  def fillJDBCOptions(reader: DataFrameReader, config: DataSourceConfig, formatName: String, dbSplitter: String): (Option[String], Option[String]) = {
Yes, I ignored other data sources, I changed it.

2021-11-21 08:56 UTC, allwefantasy approved these changes

2021-11-21 08:56 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/JDBCSource.scala
> +trait JDBCSource {
The trait name and the function names in this trait  i guess we can do better.

2021-11-21 08:57 UTC, merged